apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-09d95bd541c9046f5
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0585009b4aa206f02
      my-new-stack-PublicSubnet02:
        id: subnet-02d67ed94d09cf56d
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-033f6439459705a2d
      my-new-stack-PrivateSubnet02:
        id: subnet-08e0518bb7ff745c4

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true