apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 803387083822.dkr.ecr.us-east-1.amazonaws.com/devsu-test:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: django-config
          ports:
            - containerPort: 8000